[[redirects]]
  from = "/"
  to = "http://amazonisburning-6f8fe83a90dd.herokuapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/”
  [headers.values]
    Access-Control-Allow-Origin = "#"